

/*---------------------Even Fibonacci numbers---------------------------
 ---------------------Problem 2---------------------- 
 
 
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms. 


*/















import java.util.*;
import java.lang.*;
import java.io.*;


public class problem_no:02
{
	public static void main (String[] args) throws java.lang.Exception
	{
		
		int sum, even, fib1, fib2;
		sum=0;
		even=0;
		fib1=1;
		fib2=1;
		while (sum<4000000){
			sum = sum+fib1;
			fib1=fib2;
			fib2=sum;
		//	System.out.println(sum);
			if(sum%2==0){
			even = even+sum;	
				
			}
			
		}
		System.out.print(even);
		
	}
}
